"use client";

export default function RouteDisplay({ route, loading }) {
    if (loading) {
        return (
            <div className="w-full glass rounded-2xl p-8 animate-pulse">
                <div className="h-6 bgs late-700 rounded w-1/3 mb-6"></div>
                <div className="space-y-4">
                    {[1, 2, 3].map(i => (
                        <div key={i} className="flex items-center space-x-4">
                            <div className="w-4 h-4 rounded-full bg-slate-700"></div>
                            <div className="h-4 bg-slate-700 rounded w-full"></div>
                        </div>
                    ))}
                </div>
            </div>
        );
    }

    if (!route) return null;

    const { path, cost, name } = route;

    return (
        <div className="w-full glass rounded-3xl p-6 md:p-8 animate-in fade-in zoom-in duration-500">
            <div className="flex justify-between items-end mb-8">
                <div>
                    <h2 className="text-2xl font-bold text-sky-400">{name || "Shortest Route"}</h2>
                    <p className="text-slate-400">Estimated Travel Time</p>
                </div>
                <div className="text-right">
                    <span className="text-4xl font-black text-white">{Math.ceil(cost / 60)}</span>
                    <span className="ml-1 text-slate-400 font-medium">min</span>
                </div>
            </div>

            <div className="relative">
                {/* Vertical line connector */}
                <div className="absolute left-[11px] top-2 bottom-2 w-0.5 bg-gradient-to-b from-sky-500 via-purple-500 to-pink-500 rounded-full opacity-50"></div>

                <div className="space-y-6">
                    {path.map((stationId, index) => {
                        const isFirst = index === 0;
                        const isLast = index === path.length - 1;
                        const isTransfer = false; // logic for transfer could be added

                        return (
                            <div key={`${stationId}-${index}`} className="flex items-start space-x-6 group">
                                <div className={`relative z-10 w-6 h-6 rounded-full border-4 border-slate-900 flex-shrink-0 mt-1 smooth-transition ${isFirst || isLast ? 'bg-sky-400 scale-110 shadow-[0_0_15px_rgba(56,189,248,0.5)]' : 'bg-slate-700'}`}>
                                </div>

                                <div className="flex-grow pb-2">
                                    <div className={`font-semibold smooth-transition ${isFirst || isLast ? 'text-white text-lg' : 'text-slate-300'}`}>
                                        {stationId.split('_').pop().split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')}
                                    </div>
                                    <div className="text-xs text-slate-500 font-medium tracking-wider">
                                        {stationId.split('_')[0].toUpperCase()} • LINE {stationId.split('_')[1]}
                                    </div>
                                </div>
                            </div>
                        );
                    })}
                </div>
            </div>

            <div className="mt-8 pt-6 border-t border-slate-700/50 flex items-center justify-between text-sm">
                <div className="flex items-center space-x-4">
                    <div className="text-slate-400 italic">Route generated by Gemini AI</div>
                </div>
                <button className="text-sky-400 font-bold hover:text-sky-300 smooth-transition">
                    DETAILS
                </button>
            </div>
        </div>
    );
}
